### ISSUE TITLE
Combined directions for lines with multiple branches

### ISSUE THREAD

**Issue by JiDW** [droso-hass/idfm#25]
Hello!

Thanks a lot for your work on this integration! 
I was wondering if there is a better way to deal with lines with many branches?

i.e: on the RER B, from the Aulnay-Sous-Bois stop, if you want to get the next trains going to Paris, you need 4 different instances just for the next trains going south.

![image](https://github.com/droso-hass/idfm/assets/581736/0559a0d0-a558-4583-a052-479e108f4f72)

Thanks for your help!

**Comment by JiDW** [comment]
Thanks for looking into it, nonetheless.

I wrote a small Python script for my needs that aggregates all 4 RER B lines + line K going to Paris from my train station

In case someone wants to do the same, here it is:

```py
# List of all source sensors
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_gare_du_nord_0
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_gare_du_nord_1
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_gare_du_nord_2
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_gare_du_nord_3
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_massy_palaiseau_0
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_massy_palaiseau_1
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_massy_palaiseau_2
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_massy_palaiseau_3
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_orsay_ville_0
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_orsay_ville_1
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_orsay_ville_2
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_orsay_ville_3
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_robinson_0
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_robinson_1
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_robinson_2
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_robinson_3
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_saint_remy_les_chevreuse_0
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_saint_remy_les_chevreuse_1
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_saint_remy_les_chevreuse_2
# - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_saint_remy_les_chevreuse_3 

# Initialize the list to collect train times and their sensor names
train_times = []

# Loop through each sensor and collect their times
for i in range(4):
    for destination in ['gdn', 'gare_du_nord', 'massy_palaiseau', 'orsay_ville', 'robinson', 'saint_remy_les_chevreuse']:
        sensor_name = f'sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_{destination}_{i}'
        sensor_state = hass.states.get(sensor_name)
        if sensor_state and sensor_state.state not in ['unknown', 'unavailable']:
            try:
                # Use the raw sensor value
                train_time = sensor_state.state
                train_times.append((train_time, sensor_name, sensor_state.attributes['platform'], sensor_state.attributes['destination']))
            except ValueError:
                # Handle any parsing error
                logger.warning(f"Unable to parse time for {sensor_name}")

sorted_trains = sorted(train_times, key=lambda x: x[0])
#for index, train in enumerate(sorted_trains[:10]):
# We loop 10 times to create 10 sensors, and we use the first 10 trains in the list to populate them. If there are less than 10 trains, the extra sensors will be set to 'unknown'.
for index in range(10):
    # Get the train time and sensor name
    try:
        train = sorted_trains[index]
        # Get the destination from the sensor name
        destination = train[1].split('_')[-2]
    except IndexError:
        train = ('None', 'None', 'None', 'None')
        destination = "None"
    entity_id = f'sensor.next_train_{index + 1}'
    line = 'K' if destination == 'nord' else 'B'
    # Set the state of the sensor
    hass.states.set(entity_id, train[0], attributes={"ligne": line, "device_class": "timestamp", "platform": train[2], "destination": train[3]})
```

![image](https://github.com/droso-hass/idfm/assets/581736/a195d951-49f3-4939-847f-7fa4d4918f1f)

**Comment by drosoCode** [comment]
Thanks for sharing !

In the end, I added an option to set a custom amount of time entities (on v2.3.0).
So, you can set direction to "any" with like 10-20 entities and filter them directly in a frontend card like below (still not as flexible as your scripts since it only works for one line)
```yaml
type: entity-filter
card:
  title: Trains
state_filter:
  - operator: in
    value:
      - Robinson
      - Saint-Rémy-Lès-Chevreuse
      - Orsay-Ville
      - Massy-Palaiseau
    attribute: direction
entities:
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_0
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_1
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_2
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_3
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_4
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_5
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_6
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_7
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_8
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_9
  - sensor.idfm_aulnay_sous_bois_aulnay_sous_bois_any_10
show_empty: true
```
