### ISSUE TITLE
[enhancement] idea for idfm documentation

### ISSUE THREAD

**Issue by jugla** [droso-hass/idfm#6]
Here a template to get remaining time to next train/bus/...
It allows to get a curve .
Hereafter an example, with the sensor for train RERB at robinson station.
In configuration.yaml,
```yaml
template:
 ## IDF mobilite
  - sensor:
      - name: rer_b_robinson_deltatime
        state: "{{ ( (as_timestamp(states('sensor.idfm_robinson_chatenay_malabry_any_0')) - as_timestamp(now()))/60.0 ) | round (2) }}"
        unit_of_measurement: 'min'
        state_class: measurement
```
And the results : 
![image](https://user-images.githubusercontent.com/59493499/163713138-4be9ffb9-bd72-42ee-bee0-5c7ebd7f19e9.png)
NB: on left side, the value is not relevant (due to test to find the right formula)

**Comment by drosoCode** [comment]
Here is also an example of automation that I came up with (to prevent me from being late to my appointments because the next train was in too much time)

```yaml
alias: metro
description: "affiche un message donnant les horaires des prochains train (basé sur les informations temps réel et le temps de trajet jusqu'a la station) lorsqu'un evenement du calendrier approche et que vous etes encore chez vous"
trigger:
- platform: time_pattern
  hours: '*'
  minutes: /5
  seconds: '*'
condition:
- condition: state
  entity_id: binary_sensor.portable
  state: 'on'
- condition: state
  entity_id: calendar.cours
  state: 'off'
- "{{ (as_timestamp(state_attr('calendar.cours','start_time'), 0) - as_timestamp(now(), 0)) < (30*60) }}"
action:
- service: input_text.set_value
  data:
    value: '{% set t1 = ((as_timestamp(states(''sensor.le_kremlin_bicetre_la_courneuve_8_mai_1945_0''),
      0) - as_timestamp(now()))/60)|round %}
      {% set t2 = ((as_timestamp(states(''sensor.le_kremlin_bicetre_la_courneuve_8_mai_1945_1''),
      0) - as_timestamp(now()))/60)|round %}
      {% set t3 = ((as_timestamp(states(''sensor.le_kremlin_bicetre_la_courneuve_8_mai_1945_2''),
      0) - as_timestamp(now()))/60)|round %}

      {% if t1 >= 8 %}
      Prochain train dans {{ t1 }} min, le suivant dans {{ t2 }} min
      {% elif t2 >= 8 %}
      Prochain train dans {{ t2 }} min, le suivant dans {{ t3 }} min
      {% else %}
      Prochain train dans {{ t3 }} min
      {% endif %}
      '
  target:
    entity_id: input_text.afficheur_txt
mode: single
```

**Comment by jugla** [comment]
it's clever !

**Comment by jugla** [comment]
I don't know, if it is the right place. To display the error on line it is on several lines.
I use the custome interface (cf. HACS) `Multiline-Entity-Card`.
To modify the font size and color, I also use `card-mod`.

Then , I create the following card on dashboard (with sensor ` binary_sensor.idfm_rer_b_robinson_chatenay_malabry `).
Manual card : 
```yaml
type: custom:multiline-entity-card
name: RER B Pb
entity: binary_sensor.idfm_rer_b_robinson_chatenay_malabry
attribute: description
show_name: true
card_mod:
  style: |
    ha-card .value {
      color: blue;
      font-size : 15px;
    }
```

The result (current RER B construction site) : 
![image](https://user-images.githubusercontent.com/59493499/163719073-ae581c19-deb5-454d-9a6b-5002ddbb8a21.png)
